name: release

on:
  push:
    tags:
      - "*"

jobs:
  create:
    name: Create Release
    runs-on: ubuntu-latest
    container:
      image: secondstate/ssvm:ubuntu-build-gcc
    outputs:
      version: ${{ steps.prep.outputs.version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get version
        id: prep
        run: |
          echo ::set-output name=version::$(git describe --tag)
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: SSVM-Image ${{ steps.prep.outputs.version }}
          body_path: .CurrentChangelog.md
          draft: false
          prerelease: false
  build_and_upload_manylinux2014_x86_64:
    name: Build SSVM-Image on manylinux2014_x86_64 platform
    needs: create
    runs-on: ubuntu-latest
    container:
      image: secondstate/ssvm:manylinux2014_x86_64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build manylinux2014_x86_64 package
        run: |
          curl -s -L -O --remote-name-all https://dl.bintray.com/boostorg/release/1.75.0/source/boost_1_75_0.tar.bz2
          bzip2 -dc boost_1_75_0.tar.bz2 | tar -xf -
          yum check-update || true
          yum install -y rpm-build wget
          export PATH="/toolchain/bin:$PATH"
          export CC=gcc
          export CXX=g++
          rm -rf build
          cmake -Bbuild -DCMAKE_BUILD_TYPE=Release -DBUILD_TOOLS=Off -DBOOST_INCLUDEDIR=./boost_1_75_0/ .
          cmake --build build
          cd build
          tar -zcvf ssvm-image.tar.gz include/ssvm-image.h lib/libssvm-image_c.so
          tar Jcvf ssvm-image.tar.xz include/ssvm-image.h lib/libssvm-image_c.so
          cd ..
          mv build/ssvm-image.tar.gz ssvm-image.tar.gz
          mv build/ssvm-image.tar.xz ssvm-image.tar.xz
          wget https://github.com/second-state/ssvm-image/releases/download/0.7.3/ssvm-image-deps-0.7.3-manylinux1_x86_64.tar.gz
          tar -zxvf ssvm-image-deps-0.7.3-manylinux1_x86_64.tar.gz
          tar -zcvf ssvm-image-deps.tar.gz libjpeg.so.8.3.0 libpng16.so.16.37.0
          tar Jcvf ssvm-image-deps.tar.xz libjpeg.so.8.3.0 libpng16.so.16.37.0
          ls -alF
      - name: Upload manylinux2014_x86_64 tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: ssvm-image.tar.gz
          asset_name: ssvm-Image-${{ needs.create.outputs.version }}-manylinux2014_x86_64.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload manylinux2014_x86_64 tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: ssvm-image.tar.xz
          asset_name: ssvm-Image-${{ needs.create.outputs.version }}-manylinux2014_x86_64.tar.xz
          asset_content_type: application/x-xz
      - name: Upload deps manylinux1_x86_64 tar.gz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: ssvm-image-deps.tar.gz
          asset_name: ssvm-Image-deps-${{ needs.create.outputs.version }}-manylinux1_x86_64.tar.gz
          asset_content_type: application/x-gzip
      - name: Upload deps manylinux1_x86_64 tar.xz package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create.outputs.upload_url }}
          asset_path: ssvm-image-deps.tar.xz
          asset_name: ssvm-Image-deps-${{ needs.create.outputs.version }}-manylinux1_x86_64.tar.xz
          asset_content_type: application/x-xz
